Se crea el componente de contacto
FooCamp/foocamp-transformasion pull request #23
Opened 2021-10-05 14:32 UTC by gabalx

# FooCamp - TransformaSion

## Trello ticket
https://trello.com/c/S2jRMap5/32-3-contacto-testimonio-no-slider

## Description
Summary of the new changes, or which issues are fixed (if it's a bugfix).

## To reproduce
[WHAT]
Un hero testimonio que está conformado por una imagen, título, texto descriptivo y un autor. 

[ACCEPTANCE CRITERIA]
[Style]
- La imagen se mantiene a la izquierda con un reborde en la parte inferior izquierda. 
- El texto tiene alineación izquierda, conformado por título.
- El copy debe ser tomado del Figma. 
- El texto e imagenes debe ser modificable en Contentful. 

[Interactions]
- La funcionalidad del slider será implementada en este ticket: https://trello.com/c/CPJBLayA/27-8-contacto-slider-ppal

[Mobile considerations]
- El texto debe quedar alineado a la izquierda.

[Object structure] (Tech is accountable)

[ASSETS]
https://www.figma.com/file/uW8JW8pMxk1DjtfRIb0XB0/Transformasion?node-id=453%3A747

1. Run the project
2. Open the specific page (e.g. http://localhost:8080/gabo-page)
3. Check the component contact,above the footer

## Screenshots
Put here the screenshots of the developed functionality (or fixed issues). For each viewport (if applies).
![image](https://user-images.githubusercontent.com/68356379/136043548-44ab6e85-273b-4f51-aa58-afaeb7e94b11.png)
![image](https://user-images.githubusercontent.com/68356379/136043607-cf203fc4-93dd-4e0c-93ad-9e25c57a15c0.png)
![image](https://user-images.githubusercontent.com/68356379/136043652-b8ac6686-1996-4d79-92bd-1a0d279fd3e2.png)
![image](https://user-images.githubusercontent.com/68356379/136043702-d36eb1be-fe5e-4e4b-95cc-07f7cf1d51af.png)
![image](https://user-images.githubusercontent.com/68356379/136043781-4456ca4c-2a75-484c-b1b0-ee9693431898.png)

2021-10-05 17:52 UTC, jortizhuge approved these changes

2021-10-05 18:41 UTC, jsebax commented
In desktop, the component is not aligned with the `Grid container`. It will overflow the `max-width`, so it won't be aligned with other components.

2021-10-05 18:42 UTC, jsebax requested changes
In desktop, the component is not aligned with the Grid container. It will overflow the max-width, so it won't be aligned with other components.

2021-10-07 18:33 UTC, jsebax approved these changes

2021-10-07 18:33 UTC, merged